name: ToDo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  equatable: ^1.2.5
  get: ^3.24.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  localstorage: ^3.0.6+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^1.3.0
  mockito: ^4.1.3
  test: ^1.15.7

flutter:
  uses-material-design: true
